### ISSUE TITLE
ピティナ・東音企画メンバーの記事配信にメンバー大川を追加

### ISSUE THREAD

**Issue by Yoppei** [ptna-office/team-blog-hub#4]
# purpose

ピティナ・東音企画メンバーの記事配信に以下メンバーの記事とプロフィールを掲載する。
- 大川

# todo
- [x] id→GitHubのユーザー名 `Yoppei`
- [x] name `Yohei Okawa`
- [x] role: `undefined`
- [x] bio: `アプリiOSアプリを個人開発しています。いつもコーヒーを片手に仕事してます。`
- [x] avatarSrc: `/avatars/okawa.jpg`
- [x] sources: `["https://zenn.dev/z_ypi/feed"]`
- [x] githubUsername: `Yoppei`
- [x] twitterUsername: `y_lsisa`

# memo

# related
